<?php

/**
 * Pet Clinic Application Setup Script
 * This script helps set up the database and initial configuration
 */

// Check if setup has already been run
if (file_exists('config/.setup_complete')) {
    die('Setup has already been completed. Delete config/.setup_complete to run setup again.');
}

$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_name = $_POST['db_name'] ?? 'pet_clinic';
    $db_user = $_POST['db_user'] ?? 'root';
    $db_pass = $_POST['db_pass'] ?? '';
    $admin_username = $_POST['admin_username'] ?? 'admin';
    $admin_password = $_POST['admin_password'] ?? '';
    $admin_email = $_POST['admin_email'] ?? 'admin@petclinic.com';
    $admin_name = $_POST['admin_name'] ?? 'System Administrator';
    $install_sample_data = isset($_POST['install_sample_data']);

    try {
        // Test database connection
        $pdo = new PDO("mysql:host=$db_host", $db_user, $db_pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Create database if it doesn't exist
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$db_name`");

        // Read and execute schema
        $schema = file_get_contents('database/schema.sql');
        $pdo->exec($schema);

        // Create admin user
        $password_hash = password_hash($admin_password, PASSWORD_DEFAULT);
        $stmt = $pdo->prepare("INSERT INTO users (username, password_hash, full_name, email, role, status) VALUES (?, ?, ?, ?, 'admin', 'active')");
        $stmt->execute([$admin_username, $password_hash, $admin_name, $admin_email]);

        // Install sample data if requested
        if ($install_sample_data) {
            $sample_data = file_get_contents('database/sample_data.sql');
            // Remove the admin user insert from sample data to avoid conflict
            $sample_data = preg_replace("/INSERT INTO users.*?'admin'.*?;/s", "", $sample_data);
            $pdo->exec($sample_data);
        }

        // Create database configuration file
        $config_content = "<?php
/**
 * Database Configuration
 * Generated by setup script on " . date('Y-m-d H:i:s') . "
 */

define('DB_HOST', '$db_host');
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASS', '$db_pass');
define('DB_CHARSET', 'utf8mb4');

/**
 * Application Configuration
 */
define('APP_NAME', 'Ruang Fauna');
define('APP_VERSION', '1.0.0');
define('TIMEZONE', 'Asia/Jakarta');

/**
 * Security Configuration
 */
define('SESSION_LIFETIME', 3600); // 1 hour
define('PASSWORD_MIN_LENGTH', 6);

/**
 * File Upload Configuration
 */
define('UPLOAD_MAX_SIZE', 5 * 1024 * 1024); // 5MB
define('ALLOWED_EXTENSIONS', ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx']);

/**
 * Pagination Configuration
 */
define('RECORDS_PER_PAGE', 20);

/**
 * Currency Configuration
 */
define('CURRENCY_SYMBOL', 'Rp');
define('CURRENCY_CODE', 'idr');
?>";

        file_put_contents('config/database.php', $config_content);

        // Mark setup as complete
        file_put_contents('config/.setup_complete', date('Y-m-d H:i:s'));

        $message = "Setup completed successfully! You can now <a href='index.php'>login to the application</a> using your admin credentials.";
    } catch (PDOException $e) {
        $error = "Database error: " . $e->getMessage();
    } catch (Exception $e) {
        $error = "Setup error: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Clinic Setup</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }

        .setup-container {
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
            padding: 40px;
            width: 100%;
            max-width: 600px;
        }

        .setup-header {
            text-align: center;
            margin-bottom: 30px;
        }

        .setup-header h1 {
            color: #2c3e50;
            margin-bottom: 10px;
            font-size: 2.5em;
        }

        .setup-header p {
            color: #7f8c8d;
            font-size: 1.1em;
        }

        .form-section {
            margin-bottom: 30px;
        }

        .form-section h3 {
            color: #34495e;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #3498db;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: 600;
            color: #555;
        }

        .form-group input[type="text"],
        .form-group input[type="email"],
        .form-group input[type="password"] {
            width: 100%;
            padding: 12px;
            border: 2px solid #ddd;
            border-radius: 8px;
            font-size: 16px;
            transition: border-color 0.3s;
        }

        .form-group input:focus {
            outline: none;
            border-color: #3498db;
        }

        .form-group small {
            color: #7f8c8d;
            font-size: 0.9em;
        }

        .checkbox-group {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .checkbox-group input[type="checkbox"] {
            width: 18px;
            height: 18px;
        }

        .btn {
            background: linear-gradient(135deg, #3498db, #2980b9);
            color: white;
            padding: 15px 30px;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            width: 100%;
            transition: transform 0.2s, box-shadow 0.2s;
        }

        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(52, 152, 219, 0.3);
        }

        .alert {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }

        .alert-success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }

        .alert-error {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }

        .requirements {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }

        .requirements h4 {
            color: #495057;
            margin-bottom: 10px;
        }

        .requirements ul {
            margin-left: 20px;
            color: #6c757d;
        }

        .requirements li {
            margin-bottom: 5px;
        }
    </style>
</head>

<body>
    <div class="setup-container">
        <div class="setup-header">
            <h1>🐾 Pet Clinic Setup</h1>
            <p>Welcome! Let's set up your Pet Clinic Management System</p>
        </div>

        <?php if (!empty($message)): ?>
            <div class="alert alert-success"><?php echo $message; ?></div>
        <?php endif; ?>

        <?php if (!empty($error)): ?>
            <div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div>
        <?php endif; ?>

        <?php if (empty($message)): ?>
            <div class="requirements">
                <h4>System Requirements:</h4>
                <ul>
                    <li>PHP 7.4 or higher</li>
                    <li>MySQL 5.7 or higher</li>
                    <li>PDO MySQL extension enabled</li>
                    <li>Write permissions for config directory</li>
                </ul>
            </div>

            <form method="POST">
                <div class="form-section">
                    <h3>Database Configuration</h3>

                    <div class="form-group">
                        <label for="db_host">Database Host:</label>
                        <input type="text" id="db_host" name="db_host" value="localhost" required>
                        <small>Usually 'localhost' for local installations</small>
                    </div>

                    <div class="form-group">
                        <label for="db_name">Database Name:</label>
                        <input type="text" id="db_name" name="db_name" value="pet_clinic" required>
                        <small>Will be created if it doesn't exist</small>
                    </div>

                    <div class="form-group">
                        <label for="db_user">Database Username:</label>
                        <input type="text" id="db_user" name="db_user" value="root" required>
                    </div>

                    <div class="form-group">
                        <label for="db_pass">Database Password:</label>
                        <input type="password" id="db_pass" name="db_pass">
                        <small>Leave empty if no password is set</small>
                    </div>
                </div>

                <div class="form-section">
                    <h3>Administrator Account</h3>

                    <div class="form-group">
                        <label for="admin_username">Admin Username:</label>
                        <input type="text" id="admin_username" name="admin_username" value="admin" required>
                    </div>

                    <div class="form-group">
                        <label for="admin_password">Admin Password:</label>
                        <input type="password" id="admin_password" name="admin_password" required>
                        <small>Minimum 6 characters</small>
                    </div>

                    <div class="form-group">
                        <label for="admin_name">Admin Full Name:</label>
                        <input type="text" id="admin_name" name="admin_name" value="System Administrator" required>
                    </div>

                    <div class="form-group">
                        <label for="admin_email">Admin Email:</label>
                        <input type="email" id="admin_email" name="admin_email" value="admin@petclinic.com" required>
                    </div>
                </div>

                <div class="form-section">
                    <h3>Sample Data</h3>

                    <div class="form-group">
                        <div class="checkbox-group">
                            <input type="checkbox" id="install_sample_data" name="install_sample_data" checked>
                            <label for="install_sample_data">Install sample data for testing</label>
                        </div>
                        <small>Includes sample doctors, animals, owners, and examinations</small>
                    </div>
                </div>

                <button type="submit" class="btn">Complete Setup</button>
            </form>
        <?php endif; ?>
    </div>
</body>

</html>